### ISSUE TITLE
测试结果和建议

### ISSUE THREAD

**Issue by Quanyu-Mars** [xuthus5/fedora-deepin-tim#1]
感谢楼主的努力和付出。

测试环境:
os: fedora 29
kernel:4.20.6-200
shell: gnome 3.30.
input method: ibus-rime
测试结果: 虽有部分卡顿，但功能使用一切正常。
存在问题：在关闭tim后，第二次打开，便会报"个人文件夹被占用"错误。具体看，点关闭，并不会对tim关闭，只是关闭了UI界面，TIM还是会在进程中运行，并未关闭。
解决方法：方法1，terminal运行 pkill TIM ,方法2，重启系统。
建议，基于此，要以试着打包成fatpak包，这样可能更方便安装和使用，最好能包wine一起打包，Thks。

**Comment by xuthus5** [comment]
关于flatpak包，已经有人打包出来了。
http://tieba.baidu.com/p/5752136069
https://www.bilibili.com/video/av25095137
